### ISSUE TITLE
Missing "dropdown-trigger" class

### ISSUE THREAD

**Issue by derrickbeining** [ahstro/elm-bulma-classes#4]
Just wanted to bring to your attention a missing class that is in Bulma v0.7.5, namely, the "dropdown-trigger" class.

**Comment by ahstro** [comment]
Ah, yeah, I remember running in to this before and being really confused as to why my generator script was missing it. Turns out, `dropdown-trigger` is only in the documentation and not in [the CSS file](https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css). I created [an issue](https://github.com/jgthms/bulma/issues/1760) about it way back when, but doesn't look like it's going to be removed from the docs. Since I'm using a generator script that pulls and parses the CSS file form a CDN, I'm not going to manually add it, unless someone makes a very good argument for it :relaxed:
